linters-settings:
  depguard:
    rules:
      main:
        allow:
          - errors
          - fmt
          - regexp
          - strings
          - testing
          - encoding/hex
          - github.com/google/uuid
          - github.com/amsokol/tracecontext/traceparent
          - go.opentelemetry.io/otel/trace
